[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = true

[logger]
level = "info"

[client]
showErrorDetails = true
toolbarMode = "viewer"


[theme]
base = "light"
primaryColor = "#059669"               # Emerald-600
backgroundColor = "#FFFFFF"            # White
secondaryBackgroundColor = "#F3F4F6"   # Gray-100
textColor = "#1F2937"                  # Gray-800
font = "sans serif"